migration_level: 15
general:
  displayName: Sus
  language: vi
  keybindings:
    search:
      - ctrlKey
      - KeyF
    home:
      - ctrlKey
      - KeyH
    listenNow:
      - ctrlKey
      - KeyL
    browse:
      - ctrlKey
      - KeyN
    recentlyAdded:
      - ctrlKey
      - Digit1
    librarySongs:
      - ctrlKey
      - Digit2
    libraryAlbums:
      - ctrlKey
      - Digit3
    libraryArtists:
      - ctrlKey
      - Digit4
    immersiveMode:
      - ctrlKey
      - KeyP
    commandCenter:
      - shiftKey
      - Space
    miniPlayer:
      - ctrlKey
      - KeyK
  collapsedItems: []
  closeToTray: false
  promptOnClose: false
  warnBeforeQueueOverride: true
  startupPage: /am/home
  checkForMarketplaceUpdates: true
  checkForUpdates: true
audio:
  volume: 1
  volumeStep: 0.01
  exponentialVolume: true
  maxVolume: 1
  volumeDisplaySPL:
    enabled: false
    calibration: 90
  equalizer:
    enabled: true
    preset: default
    frequencies:
      - 32
      - 63
      - 125
      - 250
      - 500
      - 1000
      - 2000
      - 4000
      - 8000
      - 16000
    gain:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    Q:
      - 0.7071067811865476
      - 0.7071067811865476
      - 0.7071067811865476
      - 0.7071067811865476
      - 0.7071067811865476
      - 0.7071067811865476
      - 0.7071067811865476
      - 0.7071067811865476
      - 0.7071067811865476
      - 0.7071067811865476
    mix: 1
    vibrantBass: 0
    userGenerated: false
  showBitrateBadge: false
  ciderAudio:
    enabled: true
    showInToolbar: false
    showBadges: true
    ciderPPE: true
    ciderPPE_value: MAIKIWI
    staticOptimizer:
      state: false
      lock: false
    lastNode: n1
    firstNode: n1
    opportunisticCorrection_state: OFF
    atmosphereRealizer1: false
    atmosphereRealizer1_value: NATURAL_STANDARD
    atmosphereRealizer2: false
    atmosphereRealizer2_value: NATURAL_STANDARD
    spatial: false
    spatialProfile: maikiwinew
  normalization: true
  podcastsPlaybackSpeed: 1
visual:
  appearance: dark
  layoutType: mojave-if
  layoutView: HHh LpR FFf
  useAdaptiveColors: true
  adaptiveColorPercent: 10
  viewTransitions: true
  prefersReducedMotion: false
  hardwareAcceleration: default
  windowSize:
    - 1024
    - 640
  windowPosition:
    - 0
    - 0
  titleBarStyle: default
  artworkLoadingMethod: lazy
  artworkBlurMap:
    fpsLimit: 30
  backgroundBlurMap:
    enabled: false
    src: ""
    filter:
      blur: 128
      saturate: 200
      brightness: 10
      contrast: 100
  immersive:
    useAnimatedBackground: true
    useAnimatedArtwork: true
    backgroundType: default
    layoutType: default
    layoutTypePortrait: sonoma
    maxBackgroundBrightness: 50
    useBackgroundBPM: true
    startFullscreen: false
    filter:
      saturate: 180
      contrast: 1.3
  customCSS: ""
  lyricSpeedMultiplier: 1
  scalingFactor: 1
  fonts:
    main: default
    lyrics: default
  overlayDrawer: false
  scrollbarType: native
  vibrancyMode: mica
  acrylicDarkValue: 0.5
  hiresImages: false
  pauseAnimatedOnBlur: true
  sweetener:
    useImmersiveBG: true
    immersive_bg_fps: 15
    immersive_bg_filter:
      blur: 128
      saturate: 100
      brightness: 100
      contrast: 100
  ui_custom:
    useSystemAccentColor: true
    customAccentColor: false
    customAccentColorValue: "#fa2d48"
    customTintColor: false
    customTintColorValue: "#fa2d48"
    customTintColorRatio: 0.5
  ultraWide: false
  sizing: default
  transparency: true
ui:
  chromeTopWidget: search
  leftDrawerOverlay: false
  windowControlOverride: default
  mainMenuPosition: left
  forceMPWindowControls: false
components:
  AddToPlaylist:
    RecentsLimit: 3
  AMProgressBar:
    iOSStyle: true
    useAccentColor: false
  AMVolumeSlider:
    iOSStyle: false
  HeaderSearch:
    NoRedirectOnSelect: false
  ImmersiveSonoma:
    UseRadialMask: true
  Immersive:
    StartTab: queue
    MaxLyricSize: 70
    KeepCompletedLyrics: false
    ControlsTimeout: 1
    ArtworkHighlight: true
    HideSidePanelWhenNoLyrics: false
    EnableTransparency: true
    TransparencyValue: 1
    CustomImagePath: ""
    CustomImageFilter:
      blur: 0
      saturate: 100
      brightness: 100
      contrast: 100
    CustomImageMixValue: 0.5
  SimpleImmersiveBGArtwork:
    UseMask: true
    filter:
      blur: 0
      saturate: 280
      brightness: 50
      contrast: 100
  MediaItem:
    AnimateArtworkOnHover: false
  MediaItemArtwork:
    DisableFadeIn: true
    Highlights: true
  HLSVideo:
    NVFix: false
  PlaylistsPage:
    iOSLayout: false
    iOSLayoutAlways: false
    editorialLayout: false
    editorialPreference:
      - bannerUber
      - storeFlowcase
      - subscriptionHero
      - originalFlowcaseBrick
  CompactSidebar:
    size: small
    align: top
  Window:
    TitleBarControlSize: large
  ListItemProvider:
    fetchAttributes: true
  MiniPlayer:
    AnimatedArtwork: false
  MojaveLayouts:
    PlayerType: glass
    ShowQuickActions: true
  AMPLCD:
    Style: glass
  RichAlbumGrid:
    ScrollToPosition: top
    DisableScrollAnimation: false
  ThreeDQueue:
    Style: default
  SidebarProfile:
    Enabled: true
    HasMainMenu: false
    HandleVisible: true
    NameVisible: true
  ImmersiveSingAlong:
    CustomCSS: >
      .lyric_fade-enter-active {
        transition: 0.5s var(--ease_smoothEase), opacity 1s var(--ease_smoothEase),
          transform 1s var(--ease_smoothEase), filter 0.36s var(--ease_smoothEase) !important;
      }

      .lyric_fade-leave-active {
        transition: 0.5s var(--ease_smoothEase), opacity 0.5s var(--ease_smoothEase),
          transform 1s var(--ease_smoothEase), filter 0.5s var(--ease_smoothEase) !important;
      }

      .lyric_fade-enter-from {
        opacity: 0;
        transform: translateY(25%) perspective(300px) translateZ(-50px) !important;
        filter: blur(10px);
      }

      .lyric_fade-leave-to {
        opacity: 0;
        transform: translateY(-25%) perspective(300px) translateZ(-50px) rotateX(0deg) !important;
        filter: blur(10px);
      }
    CustomCSSEnabled: false
    PlayerIdleBehavior: hide
caching:
  LibraryAlbums: true
  Content: true
  ArtistChips: true
  Home: true
lyrics:
  timeOffset: 0
  thirdPartySources: true
  scaleOnAny: false
  characterFlow: false
  lineStaggering: true
  lineStaggeringImmersive: true
  singLyricsEverywhere: false
  translationEnabled: true
  translationLanguage: vi
  style:
    enabled: false
    easingFunction: ""
    easingFunctionImmersive: ""
    duration: 0.5
    durationImmersive: 1
advanced:
  flags: []
  disableLogging: false
  chromiumFlags: []
  enableMediaItemInspect: false
  switchPreset: default
  testing:
    steamDeck: false
    gameMode: false
    themeManager: false
    podcasts: false
    musicVideos: false
    forceExplicit: false
  devTools: false
  mprisEnabled: true
connectivity:
  playbackNotifications: true
  playbackNotificationType: native
  webSockets:
    enabled: true
  apiTokensRequired: true
  apiTokens: []
  discord:
    enabled: true
    client: Cider
    clearOnPause: true
    stateFormat: by {artist}
    detailsFormat: "{title}"
    timestampFormat: remaining
    buttons: []
    useAnimatedArtwork: false
    showAlbum: true
    showArtist: true
    showMultipleArtists: true
    smallImage: artists
    largeImage: animated
  lastfm:
    loggedIn: false
    username: ""
    settings:
      removeFeat: both
      scrobbleDelay: "50"
      removeExtension: false
appleMusic:
  enabled: true
  drmSystem: default
  privateEnabled: false
  animatedArtwork: true
  catalogAnimatedArtwork: false
  animatedArtworkLevel: -1
  showUserInfo: true
  seamlessAudioTransitions: true
  showStorefrontWarning: true
  popularityThreshold: 0.6
  backgroundRefreshTime: 60
  showBPM: false
  language: auto
  storefront: auto
  noPlayingAction: play-recent-tracks
  lyrics:
    singLyrics: true
    staticLyrics: false
  libraryAlbums:
    sortBy: none
    order: asc
  librarySongs:
    sortBy: none
    order: desc
    showArtwork: false
    queueLimit: 100
    itemSize: default
  libraryPlaylists:
    sortBy: none
    order: asc
  home:
    pinnedItems: []
    pinnedItemsViewType: list
    sectionsOrder:
      - pinnedItems
      - recentlyPlayed
      - artistFeed
      - madeForYou
      - fromShazam
      - friendsListeningTo
    followedArtists: []
    buttonLocation: sidebar
    artwork:
      enabled: false
      url: ""
      video: false
      position: center
  browse:
    hideHeroItems: false
    moveUpLinks: false
  useAMPComponents: {}
  podcasts:
    following: []
spotify:
  enabled: false
  playlists: []
  relationships: []
  loggedin: false
  refreshToken: ""
casting:
  enabled: false
remote:
  enabled: false
  autostartTunnel: true
  tunnelUUID: ""
updates:
  updateChannel: stable
  checkForUpdates: true
DVTCfg:
  V250: {}
plugins:
  cidr.amaru8.adaptiveaccentseverywhere:
    frozen: false
    algorithm: musicKit
    mkAlgo_keyColor: textColor1
    mkAlgo_musicKeyColor: textColor4
    internal_SchemeMatching: generic
  me.thebroz.better-visualizer:
    visualizerDampening: 0.45
    visualizerColoring: cider-red
